# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Showcased
email: showcased@podium.video
description: > # this means to ignore newlines until "baseurl:"
  Exchange your portfolio just by touching phones. Your showcased
  card contains your entire portfolio. Show examples of your
  work. Say what you do.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://showcased.com" # the base hostname & protocol for your site
author: Isaiah Turner
twitter_username: IsaiahJTurner
github_username:  IsaiahJTurner

# Build settings
markdown: kramdown
